### PR TITLE
new: add dynamic request option to let consumers use additional endpoints

### PR DESCRIPTION
**Pull request by ItamarShDev**
### Description

add dynamic request option to let consumers use additional endpoints
### Checklist

- [x] Code compiles correctly
- [ ] Created tests which fail without the change (if applicable)
- [x] All lint and unit tests passing
- [x] Extended the README / documentation, if necessary

### Additional Comments

Anything else you'd like to add.

### CODE REVIEW

**Comment by bgrnwd** [comment]
@ItamarShDev Thanks for both PRs. Mind fixing the merge conflicts here?

**Comment by ItamarShDev** [comment]
> @ItamarShDev Thanks for both PRs! Mind fixing the merge conflicts here?

Done

**Review by bgrnwd — APPROVED** [review]

**Comment by ItamarShDev** [comment]
Thanks! when will this version be released?

**Comment by bgrnwd** [comment]
@ItamarShDev It should be out there. I published `2.1.1.` last night

**Pull request merged**
